title: My blog
description: My very nice blog
author: "Andrew Tkachenko"

theme: minima

base_url: /gh-pages-minima-starter

# Minima social links
github_username: AndrewStSp

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  
include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
